---
- name: Download the stern archive.
  get_url:
    url: "{{ stern_download_url }}"
    dest: /tmp
    checksum: sha256:{{ stern_checksum_url }}
    mode: 0755
  register: stern_download

- name: Unarchive the stern archive.
  unarchive:
    src: "{{ stern_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true
  register: abc

- name: Copy the stern binary into place.
  copy:
    src: /tmp/stern
    dest: "{{ stern_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
